# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnApp' do
  pod 'AppCenter/Crashes', '~> 2.2.0'
  pod 'AppCenter/Analytics', '~> 2.2.0'
  pod 'AppCenterReactNativeShared', '~> 2.2.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rnApp

  

  platform :ios, '9.0'
  target 'rnAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rnApp-tvOS

  target 'rnApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
